name: Demo Org Secret

on:
  workflow_dispatch:    # enables the "Run workflow" button

jobs:
  show-org-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print masked org secret
        run: echo "Org secret is:${{ secrets.DB_PW }}"
